### ISSUE TITLE
Disabling cache in application.properties doesn't work in version 2.4

### ISSUE THREAD

**Issue by maxmumford** [PebbleTemplates/pebble-spring-boot-starter#13]
Hiya,

In an empty spring boot project with pebble, disabling the cache in application.properties doesn't seem to work. I would expect to be able to change a .pebble file contents and see those changes when I refresh the page without restarting the server, but the content stays the same until a server restart.

I've reproduced the problem and created a repo for it here:

https://github.com/maxmumford/spring-pebble-cache-bug

Just run the project, visit the root path of the site, change the contents of the index.pebble file, refresh the page and see that it doesn't update with the new content.

I've checked inside the PebbleAutoConfiguration.java page and the cache property is correctly picked up to be false, however it doesn't appear to have any effect.

Thanks
Max

**Comment by hectorlf** [comment]
Hmm, works for me with a little gotcha: you have to execute a gradlew assemble for tomcat to notice the changes (without stopping the server).

I've been pretty much disconnected from Spring Boot for months but, AFAIR, resources in src/resources weren´t picked automatically by the bootRun task. Am I missing something?

**Comment by hectorlf** [comment]
Oh, yeah, you're right, it's in the docs!

Your build.gradle was lacking this:

bootRun {
    addResources = true
}

What a neat trick, I overlooked that completely. Thanks!

**Comment by maxmumford** [comment]
Thanks a lot, @hectorif that worked - I can now refresh the page and get updates without restarting the server or running the assemble task. Can I just check something with you though: I added:

`
	bootRun {
		addResources = true
	}
`

... to within my build.gradle files "dependencies" section as it was the only place that gradle seemed to like it, and it worked, but it feels... wrong. Also intellij is complaining that the "Method call is ambiguous". Is that where it should be??

**Comment by maxmumford** [comment]
Nevermind - it does work if it's added to the root of the file, just has to be at the end of the file instead :) Thanks for your help.
