### ISSUE TITLE
cache = false not working as expected

### ISSUE THREAD

**Issue by akuehntopf** [PebbleTemplates/pebble-spring-boot-starter#2]
It seems as if setting "pebble.cache=false" in application.properties does not have any effect. The template is still being cached.

At first glance it seems that a call to builder.cacheActive(false) is missing in 

``` if (!properties.isCache()) {
                builder.templateCache(null);
                builder.tagCache(null);
}```
(in PebbleAutoConfiguration.java).

Can you confirm this issue?

**Comment by hectorlf** [comment]
Yes, that part of the code is not up to date with the current pebble api. Thank you!!
