### ISSUE TITLE
Release 2.2.2 on maven central

### ISSUE THREAD

**Issue by jochen777** [PebbleTemplates/pebble-spring-boot-starter#3]
Is it right that the 2.2.2 of pebble-spring-boot-starter fixes the caching-preference?
If so - please upload this to maven-central! It would be nice, to get this feature.

thank you for your work on this nice lib!!

**Comment by hectorlf** [comment]
Releases are tied to the main Pebble project, so I´m invoking @mbosecke on this one.

Thanks!!

**Comment by mbosecke** [comment]
I've just now released 2.2.2; it should be in maven central within a couple of hours.

**Comment by jochen777** [comment]
It fixed the issue with the caching-parameter. Thank you!!! I love it.
