### ISSUE TITLE
Can the template engine be used without web-environment?

### ISSUE THREAD

**Issue by robertotru** [PebbleTemplates/pebble-spring-boot-starter#6]
Hi all,

I use Pebble as well as other engines (Mustache, Freemarker, etc.) in a library for sending emails.
In [this issue](https://github.com/ozimov/spring-boot-email-tools/issues/44) I have been notified that when setting `spring.main.web-environment=false` the `TemplateService` is not set for Pebble. This issue doesn't happen with other template engines. 

Is there any known reason for this?

**Comment by hectorlf** [comment]
Hi! Yes, the pebble-spring-boot-starter expects a web environment, mainly because we depend on some servlet artifacts and spring view resolvers on the org.springframework.web package. Are you using a boot starter to autoconfigure Mustache? If the answer is yes, I can have a look at how they configure boot and make some changes.

**Comment by robertotru** [comment]
Yeah, so, actually I use the official Spring Boot dependency for Mustache.

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mustache</artifactId>
            <version>LATEST</version>
        </dependency>
```

To compile a template, I then need to autowire a `MustacheAutoConfiguration`.

**Comment by hectorlf** [comment]
Hmmm, I'm not able to reproduce this. I've committed a test that obtains a PebbleEngine when the web environment is disabled. See [this commit](https://github.com/PebbleTemplates/pebble-spring-boot-starter/commit/f2d6870c0275413409e9f61fe6e2ed88053204e2)

Are you trying to use the *pebbleViewResolver* directly in any way?

**Comment by robertotru** [comment]
For Pebble I use PebbleViewResolver 
https://github.com/ozimov/spring-boot-email-tools/blob/master/spring-boot-email-template-engines/spring-boot-pebble-email/src/main/java/it/ozimov/springboot/mail/templating/service/PebbleTemplateService.java

For Mustache I call MustacheAutoconfiguration

https://github.com/ozimov/spring-boot-email-tools/blob/master/spring-boot-email-template-engines/spring-boot-mustache-email/src/main/java/it/ozimov/springboot/mail/templating/service/MustacheTemplateService.java

**Comment by hectorlf** [comment]
You are autowiring *pebbleViewResolver* but not using it in the code. Remove the field and it should work.

**Comment by robertotru** [comment]
Right! I'll do a try! Thanks

**Comment by robertotru** [comment]
@hectorlf  I know remember why I autowired `PebbleViewResolver`. Because without it the default prefix (`templates`) was not provided to the PebbleEngine and I did not want to request an extra application param from the users.

I just remembered this after removing the bean from my class. 

Any suggestion?

**Comment by hectorlf** [comment]
Yeah, that's a very valid point and, actually, the starter code was not reflecting 100% what was said in the README docs. I've changed the autoconfigured Loader to pick prefix and suffix from the properties file, so your issue should be solved.

Releases are handled by @mbosecke, so I'll invoke him to coordinate.

Thanks!

**Comment by robertotru** [comment]
You are more than welcome. I really love Pebble and I'm happy to provide support for it.

**Comment by hectorlf** [comment]
Version 2.4.0 was released a few days ago. Could you test it and see if it solves the issue?

**Comment by robertotru** [comment]
Ok, I will!

**Comment by robertotru** [comment]
Everything seems to be ok! Thanks
