### ISSUE TITLE
Add strictVariables property in default configuration

### ISSUE THREAD

**Issue by xfornesa** [PebbleTemplates/pebble-spring-boot-starter#8]
When working in templates I like to enable strictVariables to make it crash when I use something that is not previously declared instead of silently failing (which simply considers a blank). It is a pain to override the default pebble engine bean, which works as is, only to enable this behaviour.

I made a PR #7 just to add this property in PebbleProperties class with the default expected value at this moment which is false.

Would you like to move it forward please? :D

**Comment by hectorlf** [comment]
Merged! Thank you very much!

Releases are tied to the Pebble project, so I'll invoke @mbosecke to take care of it.

**Comment by xfornesa** [comment]
Great cool 👍
